import { defineConfig, Platform } from 'taqwright';

// Generated by LIME — taqwright project config.
// Add iOS / iPad projects by appending more entries to `projects[]`.
export default defineConfig({
  testDir: './tests',
  // Generous per-test cap: BrowserStack device allocation + app install + driver
  // init can take well over 60s before the test body even runs. Local runs finish
  // in ~12s, so the higher ceiling is harmless there.
  timeout: 180_000,
  expectTimeout: 30_000,
  reporter: [['list'], ['html', { open: 'never' }]],
  workers: 1,
  projects: [
    {
      name: 'android',
      testDir: './tests/android',
      use: {
        platform: Platform.ANDROID,
        device: {
          provider: 'emulator',
          name: 'Pixel_10_Pro_XL',   // AVD id — required for autoStartDevice to cold-boot
          udid: 'emulator-5554',     // pin/attach to this serial once booted
        },
        appium: {
          autoStart: true,
          autoStartDevice: true,
          host: 'localhost',
          port: 4723,
          path: '/',
        },
        buildPath: process.env.TAQ_APK || './app/DemoApp-v1.0.0.apk',
        appBundleId: 'com.taqelah.demo_app',
        resetBetweenTests: true,
      },
    },
    {
      // Cloud execution on BrowserStack — Android real device. The taqwright
      // runner reads credentials from env vars BROWSERSTACK_USERNAME /
      // BROWSERSTACK_ACCESS_KEY (NOT from LIME's stored creds).
      //   BROWSERSTACK_USERNAME=… BROWSERSTACK_ACCESS_KEY=… \
      //   npx taqwright test --project browserstack-android
      name: 'browserstack-android',
      testDir: './tests/android',
      use: {
        platform: Platform.ANDROID,
        device: {
          provider: 'browserstack',
          name: 'Google Pixel 8',
          osVersion: '14.0',
        },
        // Pre-uploaded BrowserStack app id — used directly, so no per-run upload.
        // Override with a local .apk path (or a different bs:// id) via TAQ_APK.
        buildPath: process.env.TAQ_APK || 'bs://8a9b6533441ab5496bfd082f163cb2273fade27e',
        appBundleId: 'com.taqelah.demo_app',
        resetBetweenTests: true,
        // Capture per-action screenshot + page-source timeline (and video) for
        // debugging cloud runs. View with `npx taqwright show-report`.
        trace: 'on',
        video: 'on-failure',
        // Experiment: ask UiAutomator2 to surface more of the accessibility node
        // in the page source (extras + invisible nodes). NOTE: bracket syntax —
        // `appium:settings[<name>]` — the nested `appium:settings: {}` form is
        // NOT applied. This can't invent a hint the node doesn't expose, but may
        // reveal hint-like data under extras.
        capabilities: {
          'appium:settings[includeExtrasInPageSource]': true,
          'appium:settings[allowInvisibleElements]': true,
          // BrowserStack runs Appium 2.x for Android (it rejects "3"). Pin a
          // specific 2.x to test whether it exposes the field `hint`.
          'bstack:options': { appiumVersion: '2.19.0' },
        },
      },
    },
    {
      // Local iOS simulator. taqwright uses provider 'emulator' for simulators
      // too; XCUITest auto-boots the named simulator. Needs the .app (simulator
      // build) and the iOS bundle id (note: camelCase, differs from Android).
      name: 'ios',
      testDir: './tests/ios',
      use: {
        platform: Platform.IOS,
        device: {
          provider: 'emulator',
          name: 'iPhone 17 Pro',
          udid: '5BE03619-BC3C-42E5-8B1E-747C1F9EA698',
        },
        appium: {
          autoStart: true,
          host: 'localhost',
          port: 4723,
          path: '/',
        },
        buildPath: './app/DemoApp-v1.0.0.app',
        appBundleId: 'com.taqelah.demoApp',
        resetBetweenTests: true,
      },
    },
    {
      // Cloud execution on BrowserStack — iOS real device. The .ipa is an
      // unsigned device build (flutter build ios --no-codesign … --no-tree-shake-icons,
      // zipped as Payload/Runner.app); BrowserStack re-signs it on upload.
      // Creds via env BROWSERSTACK_USERNAME / BROWSERSTACK_ACCESS_KEY.
      name: 'browserstack-ios',
      testDir: './tests/ios',
      use: {
        platform: Platform.IOS,
        device: {
          provider: 'browserstack',
          name: 'iPhone 15',
          osVersion: '17',
        },
        // Pre-uploaded BrowserStack iOS app id — used directly, so no per-run
        // upload. Override with a local .ipa path (or another bs:// id) via TAQ_IPA.
        buildPath: process.env.TAQ_IPA || 'bs://9ed3bef10e3573786f0918cba5721ac0c0aa3525',
        appBundleId: 'com.taqelah.demoApp',
        resetBetweenTests: true,
      },
    },
  ],
});
