import { defineConfig, Platform } from '@taqwright/taqwright';

// Generated by LIME — taqwright project config.
// Add iOS / iPad projects by appending more entries to `projects[]`.
export default defineConfig({
  testDir: './tests',
  // Generous per-test cap: BrowserStack device allocation + app install + driver
  // init can take well over 60s before the test body even runs. Local runs finish
  // in ~12s, so the higher ceiling is harmless there.
  timeout: 180_000,
  expectTimeout: 30_000,
  // Re-run a failed test once. taqwright rides out transient device "offline"
  // blips during session init + reset (framework gate+retry); `retries` is the
  // backstop for a flake mid-test-body, which command-level retry can't cover —
  // the rerun lands on the (by then recovered) emulator.
  retries: 1,
  reporter: [['list'], ['html', { open: 'never' }]],
  // taqwright >= 0.0.9 supports PER-PROJECT `workers` (effective =
  // project.workers ?? config.workers ?? 1). We leave the global default at 1
  // and set `workers` only on the project that needs it (`android-parallel`).
  // The CLI injects `--workers <project's count>` for a single `--project` run,
  // so Playwright's global pool matches that one project. A project's `workers`
  // must be <= its device count (pool length / autoDiscover-resolved devices).
  fullyParallel: true,
  projects: [
    {
      // (1) Single local emulator, pinned to ONE given serial. No `workers`
      // → global default of 1. autoStartDevice cold-boots the named AVD if it
      // isn't already running, then attaches to `udid`.
      //   npx taqwright test --project android-single
      name: 'android-single',
      testDir: './tests/android',
      use: {
        platform: Platform.ANDROID,
        device: {
          provider: 'emulator',
          name: 'Pixel_10_Pro_XL',   // AVD id — required for autoStartDevice to cold-boot
          udid: 'emulator-5554',     // pin/attach to this serial once booted
        },
        appium: {
          autoStart: true,
          autoStartDevice: true,
          host: 'localhost',
          port: 4723,
          path: '/',
        },
        buildPath: process.env.TAQ_APK || './app/DemoApp-v1.0.0.apk',
        appBundleId: 'com.taqelah.demo_app',
        resetBetweenTests: true,
      },
    },
    {
      // (2) Fixed pool of TWO emulators, run 2-wide. `workers` (2) must be <=
      // pool length — one worker per pool entry. Each entry names its AVD (the
      // Google Pixel); with `autoStartDevice`, taqwright pre-boots both AVDs
      // up front (globalSetup) and waits until each is ready before the workers
      // attach — so a cold start never hits the concurrent-boot "device offline"
      // race. Two parallel emulators need two distinct AVDs. Worker i spawns
      // Appium on 4723+i.
      //   npx taqwright test --project android-pool-2
      name: 'android-pool-2',
      testDir: './tests/android',
      workers: 2,
      use: {
        platform: Platform.ANDROID,
        device: {
          provider: 'emulator',
          pool: [
            { name: 'Pixel_10_Pro_XL', udid: 'emulator-5554' },     // AVD id + serial
            { name: 'Pixel_10_Pro_XL_2', udid: 'emulator-5556' },
          ],
        },
        appium: {
          autoStart: true,       // worker i spawns Appium on 4723 + i
          autoStartDevice: true, // cold-boot each pool entry by its AVD `name`
          host: 'localhost',
          port: 4723,            // base port; per-worker offset added automatically
          path: '/',
        },
        buildPath: process.env.TAQ_APK || './app/DemoApp-v1.0.0.apk',
        appBundleId: 'com.taqelah.demo_app',
        resetBetweenTests: true,
        // Per-action screenshot + page-source timeline + screen recording →
        // HTML report. View with `npx taqwright show-report`.
        trace: 'on-failure',
        video: 'on-failure',
      },
    },
    {
      // (3) Auto-detect devices, SERIAL (workers: 1). autoDiscover enumerates
      // the host's AVDs at run start; with 1 worker it uses the first one. No
      // pool, no fixed udid — whatever emulator is booted is used.
      //   npx taqwright test --project android-auto-1
      name: 'android-auto-1',
      testDir: './tests/android',
      workers: 1,
      use: {
        platform: Platform.ANDROID,
        device: {
          provider: 'emulator',
          autoDiscover: true,   // resolve & assign `workers` AVDs automatically — no pool
        },
        appium: {
          autoStart: true,
          host: 'localhost',
          port: 4723,
          path: '/',
        },
        buildPath: process.env.TAQ_APK || './app/DemoApp-v1.0.0.apk',
        appBundleId: 'com.taqelah.demo_app',
        resetBetweenTests: true,
        trace: 'on-failure',
        video: 'on-failure',
      },
    },
    {
      // (4) Auto-detect devices, 2-wide (workers: 2). autoDiscover resolves the
      // host's AVDs and assigns `workers` (2) of them — needs >= 2 booted AVDs.
      // Worker i spawns Appium on 4723 + i.
      //   npx taqwright test --project android-auto-2
      name: 'android-auto-2',
      testDir: './tests/android',
      workers: 2,
      use: {
        platform: Platform.ANDROID,
        device: {
          provider: 'emulator',
          autoDiscover: true,   // resolve & assign `workers` AVDs automatically — no pool
        },
        appium: {
          autoStart: true,       // worker i spawns Appium on 4723 + i
          host: 'localhost',
          port: 4723,            // base port; per-worker offset added automatically
          path: '/',
        },
        buildPath: process.env.TAQ_APK || './app/DemoApp-v1.0.0.apk',
        appBundleId: 'com.taqelah.demo_app',
        resetBetweenTests: true,
        trace: 'on-failure',
        video: 'on-failure',
      },
    },
    {
      // Cloud execution on BrowserStack — Android real device. The taqwright
      // runner reads credentials from env vars BROWSERSTACK_USERNAME /
      // BROWSERSTACK_ACCESS_KEY (NOT from LIME's stored creds).
      //   BROWSERSTACK_USERNAME=… BROWSERSTACK_ACCESS_KEY=… \
      //   npx taqwright test --project browserstack-android
      name: 'browserstack-android',
      testDir: './tests/android',
      // Cloud parallelism: 5 concurrent BrowserStack sessions (one device per
      // worker from BS's parallel queue — no device.pool needed for cloud).
      // Must be <= your BrowserStack plan's parallel-session limit, or extra
      // sessions queue/fail. fullyParallel spreads the 5 specs across them.
      workers: 5,
      // Per-test budget must cover BrowserStack device allocation (slow under
      // parallel queueing) + the test body — otherwise Playwright kills the test
      // before the longer connection timeout below can help. Overrides the
      // global 180s.
      timeout: 300_000,
      use: {
        platform: Platform.ANDROID,
        device: {
          provider: 'browserstack',
          name: 'Google Pixel 8',
          osVersion: '14.0',
        },
        // Raise the WebDriver client session-creation timeout (wdio
        // `connectionRetryTimeout`, default 120s): allocating 5 parallel real
        // devices can exceed it and abort the `/session` POST. Cloud-only knob
        // here — the other `appium.*` fields don't apply to a cloud provider.
        appium: { connectionTimeout: 240_000 },
        // Pre-uploaded BrowserStack app id — used directly, so no per-run upload.
        // Override with a local .apk path (or a different bs:// id) via TAQ_APK.
        buildPath: process.env.TAQ_APK || 'bs://8a9b6533441ab5496bfd082f163cb2273fade27e',
        appBundleId: 'com.taqelah.demo_app',
        resetBetweenTests: true,
        // Capture per-action screenshot + page-source timeline (and video) for
        // debugging cloud runs. View with `npx taqwright show-report`.
        trace: 'on',
        video: 'on-failure',
        // Experiment: ask UiAutomator2 to surface more of the accessibility node
        // in the page source (extras + invisible nodes). NOTE: bracket syntax —
        // `appium:settings[<name>]` — the nested `appium:settings: {}` form is
        // NOT applied. This can't invent a hint the node doesn't expose, but may
        // reveal hint-like data under extras.
        capabilities: {
          'appium:settings[includeExtrasInPageSource]': true,
          'appium:settings[allowInvisibleElements]': true,
          // BrowserStack runs Appium 2.x for Android (it rejects "3"). Pin a
          // specific 2.x to test whether it exposes the field `hint`.
          'bstack:options': {
            appiumVersion: '2.19.0',
            // BrowserStack-side session idle timeout (seconds): how long BS
            // waits for the next command before terminating the session. Max
            // 300 for App Automate. Raised so slow allocation/steps under
            // 5-way parallel load don't trip the default. Overrides taqwright's
            // default (180) via the provider's deep-merge of bstack:options.
            idleTimeout: 300,
          },
        },
      },
    },
    {
      // Cloud execution on LambdaTest — Android real device. Credentials come
      // from env vars LAMBDATEST_USERNAME / LAMBDATEST_ACCESS_KEY (the provider
      // fails fast at globalSetup if either is missing).
      //   LAMBDATEST_USERNAME=… LAMBDATEST_ACCESS_KEY=… \
      //   npx taqwright test --project lambdatest-android
      name: 'lambdatest-android',
      testDir: './tests/android',
      // Same cloud-parallelism rule as BrowserStack: must be <= your LambdaTest
      // plan's concurrent-session limit, or the extra sessions sit in the queue
      // (LambdaTest waits up to `queueTimeout`, 600s, before failing).
      workers: 5,
      // Real-device allocation + app install happen before the test body, same
      // as the BrowserStack project — keep the wider budget rather than the
      // global 180s.
      timeout: 300_000,
      use: {
        platform: Platform.ANDROID,
        device: {
          provider: 'lambdatest',
          // LambdaTest's own device naming — the provider also aliases
          // 'Google Pixel 8' → 'Pixel 8' and '14.0' → '14', so the BrowserStack
          // spelling would work too; use LambdaTest's to keep it obvious.
          name: 'Pixel 8',
          osVersion: '14',
        },
        // Cloud-only knob (wdio `connectionRetryTimeout`; the provider defaults
        // it to 300s already). The rest of `appium.*` is local-only and does
        // not apply here.
        appium: { connectionTimeout: 240_000 },
        // Pre-uploaded LambdaTest app id (DemoApp-v1.0.1) — anything starting
        // with `lt://` is passed straight through, so there's no per-run upload.
        // NOTE: this is v1.0.1, newer than the v1.0.0 .apk checked into app/.
        // Override with a local .apk path (which globalSetup then uploads once
        // per run) or a different lt:// id via TAQ_APK.
        buildPath: process.env.TAQ_APK || 'lt://APP10160362051783065242028848',
        appBundleId: 'com.taqelah.demo_app',
        resetBetweenTests: true,
        trace: 'on',
        video: 'on-failure',
        // Bracket syntax — the nested `appium:settings: {}` form is NOT applied.
        // Anything here that isn't namespaced (no ':') is folded into
        // `lt:options` by the provider, so LambdaTest-specific knobs can be set
        // either bare or under an explicit `lt:options` object.
        capabilities: {
          'appium:settings[includeExtrasInPageSource]': true,
          'appium:settings[allowInvisibleElements]': true,
        },
      },
    },
    {
      // Local iOS simulator. taqwright uses provider 'emulator' for simulators
      // too; XCUITest auto-boots the named simulator. Needs the .app (simulator
      // build) and the iOS bundle id (note: camelCase, differs from Android).
      name: 'ios',
      testDir: './tests/ios',
      use: {
        platform: Platform.IOS,
        device: {
          provider: 'emulator',
          name: 'iPhone 17 Pro',
          udid: '5BE03619-BC3C-42E5-8B1E-747C1F9EA698',
        },
        appium: {
          autoStart: true,
          host: 'localhost',
          port: 4723,
          path: '/',
        },
        buildPath: './app/DemoApp-v1.0.0.app',
        appBundleId: 'com.taqelah.demoApp',
        resetBetweenTests: true,
      },
    },
    {
      // Cloud execution on BrowserStack — iOS real device. The .ipa is an
      // unsigned device build (flutter build ios --no-codesign … --no-tree-shake-icons,
      // zipped as Payload/Runner.app); BrowserStack re-signs it on upload.
      // Creds via env BROWSERSTACK_USERNAME / BROWSERSTACK_ACCESS_KEY.
      name: 'browserstack-ios',
      testDir: './tests/ios',
      use: {
        platform: Platform.IOS,
        device: {
          provider: 'browserstack',
          name: 'iPhone 15',
          osVersion: '17',
        },
        // Pre-uploaded BrowserStack iOS app id — used directly, so no per-run
        // upload. Override with a local .ipa path (or another bs:// id) via TAQ_IPA.
        buildPath: process.env.TAQ_IPA || 'bs://9ed3bef10e3573786f0918cba5721ac0c0aa3525',
        appBundleId: 'com.taqelah.demoApp',
        resetBetweenTests: true,
      },
    },
    {
      // Cloud execution on LambdaTest — iOS real device. Needs the same
      // unsigned .ipa device build as the BrowserStack iOS project (LambdaTest
      // re-signs it on upload). Creds via env LAMBDATEST_USERNAME /
      // LAMBDATEST_ACCESS_KEY.
      //   npx taqwright test --project lambdatest-ios
      name: 'lambdatest-ios',
      testDir: './tests/ios',
      use: {
        platform: Platform.IOS,
        device: {
          provider: 'lambdatest',
          name: 'iPhone 15',
          osVersion: '17',
        },
        // No .ipa is checked in (app/ holds the .app simulator build, which a
        // real device can't run), so this project needs TAQ_IPA — either a
        // local .ipa path to upload, or an already-uploaded `lt://` app id.
        buildPath: process.env.TAQ_IPA || '',
        appBundleId: 'com.taqelah.demoApp',
        resetBetweenTests: true,
      },
    },
  ],
});
